### ISSUE TITLE
Redmine 4.2.x

### ISSUE THREAD

**Issue by Cmon169** [alexmonteiro/Redmine-Monitoring-Controlling#132]
Please kindly allow 4.2.x to use this plugin.
After issue creation it comes up with Internal Error when try to look at page.

I am running   
Bitnami Redmine version  4.2.3.stable
Ruby version                   2.6.9-p207 (2021-11-24) [x64-mingw32]
Rails version                  5.2.6
MSSQL2017

Thanks.

Started GET "/redmine/projects/test-monitoring-and-controlling-by-project" for 127.0.0.1 at 2022-03-11 04:10:39 -0500
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"test-monitoring-and-controlling-by-project"}
  Current user: admin (id=1)
  Rendering projects/show.html.erb within layouts/base
  Rendered plugins/redmine_contacts/app/views/projects/_contacts.html.erb (2.5ms)
  Rendered projects/_members_box.html.erb (1.8ms)
  Rendered projects/show.html.erb within layouts/base (144.7ms)
  Rendered plugins/redmine_contacts/app/views/common/_additional_assets.html.erb (2.4ms)
  Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (1.5ms)
  Rendered plugins/redmine_favorite_projects/app/views/favorite_projects/_additional_assets.html.erb (0.3ms)
  Rendered plugins/redmine_zenedit/app/views/zenedit/_additional_assets.html.erb (0.2ms)
  Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (0.9ms)
  Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.4ms)
  Rendered plugins/redmine_favorite_projects/app/views/favorite_projects/_select2_transformation_rules.html.erb (0.4ms)
  Rendered plugins/redmine_products/app/views/products/_select2_transformation_rules.html.erb (0.5ms)
Completed 200 OK in 871ms (Views: 169.2ms | ActiveRecord: 588.7ms)
Started GET "/redmine/home_monitoring_controlling_project/index/test-monitoring-and-controlling-by-project" for 127.0.0.1 at 2022-03-11 04:10:43 -0500
Processing by HomeMonitoringControllingProjectController#index as HTML
  Parameters: {"id"=>"test-monitoring-and-controlling-by-project"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 167ms (ActiveRecord: 133.8ms)
  
ActiveRecord::StatementInvalid (TinyTds::Error: Incorrect syntax near the keyword 'percent'.: SELECT *,
                                            ((SELECT COUNT(1) FROM issues where project_id in (7) and status_id = issue_statuses.id)
                                            /
                                            1)*100 as percent,
                                            (SELECT COUNT(1) FROM issues where project_id in (7) and status_id = issue_statuses.id)
                                            AS totalissues
                                            FROM issue_statuses;):
  
plugins/redmine_monitoring_controlling/app/controllers/home_monitoring_controlling_project_controller.rb:51:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by Cmon169** [comment]
After updating the .rb files in the controller folder in MSSQL format it seems to work in Redmine.
Thanks.
